nginx:
  container_name: nginx
  image: genee/nginx
  ports:
  - 80:80/tcp
  privileged: true
  restart: always
  volumes:
  - /dev/log:/dev/log
  - /etc/localtime:/etc/localtime:ro
  - /data:/data
  - ./etc/nginx/conf.d:/etc/nginx/conf.d:ro
  - ./etc/nginx/default.d:/etc/nginx/default.d:ro
  - ./etc/nginx/include.d:/etc/nginx/include.d:ro
  - /data/var/log/nginx:/var/log/nginx

