hub-product:
  container_name: sphinx
  image: genee/sphinxsearch
  ports:
  - 9312:9312/tcp
  - 9306:9306/tcp
  restart: always
  environment:
    - "SPHINX_SERVER_ID=1"
    - "PRODUCT_SERVER_HOST=product.hub.{{{LABMAIDOMAIN}}}"
    - "PRODUCT_SERVER_PORT=80"
  volumes:
  - /data/var/log/sphinxsearch:/var/log/sphinxsearch
  - /dev/log:/dev/log
  - ./etc/sphinxsearch:/etc/sphinxsearch
  - /data/var/lib/sphinxsearch:/var/lib/sphinxsearch
  #- ./etc/hosts:/etc/hosts:ro
  - /tmp:/tmp
  dns: {{{DOCKER0IP}}}
