version: '2'
services:
  owl:
    container_name: hedwig-owl
    restart: always
    image: genee/hedwig-owl
    ports:
    - {{{DOCKER0IP}}}:25:25
    volumes:
    - /etc/localtime:/etc/localtime:ro
    - /dev/log:/dev/log
    - ./etc/hedwig:/etc/hedwig
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"
